import type {Tome} from '@fuzdev/fuz_ui/tome.js';
import IntroductionPage from '$routes/docs/introduction/+page.svelte';
import ArchitecturePage from '$routes/docs/architecture/+page.svelte';
import CliPage from '$routes/docs/cli/+page.svelte';
import VitePluginPage from '$routes/docs/vite-plugin/+page.svelte';
import SessionPage from '$routes/docs/session/+page.svelte';
import BuildToolsPage from '$routes/docs/build-tools/+page.svelte';
import OutputFormatPage from '$routes/docs/output-format/+page.svelte';
import TagsPage from '$routes/docs/tags/+page.svelte';
import DiagnosticsPage from '$routes/docs/diagnostics/+page.svelte';
import ApiPage from '$routes/docs/api/+page.svelte';

export const tomes: Array<Tome> = [
	{
		slug: 'introduction',
		category: 'guide',
		Component: IntroductionPage,
		related_tomes: [
			'architecture',
			'cli',
			'vite-plugin',
			'session',
			'build-tools',
			'output-format',
			'tags',
			'api',
		],
		related_modules: ['analyze.ts', 'session.ts'],
		related_declarations: [
			'analyzeFromFiles',
			'analyze',
			'createAnalysisSession',
			'createSourceOptions',
		],
	},
	{
		slug: 'cli',
		category: 'guide',
		Component: CliPage,
		related_tomes: ['introduction', 'vite-plugin', 'output-format', 'diagnostics'],
		related_modules: ['cli.ts'],
		related_declarations: ['analyzeFromFiles'],
	},
	{
		slug: 'vite-plugin',
		title: 'vite plugin',
		category: 'guide',
		Component: VitePluginPage,
		related_tomes: ['introduction', 'cli', 'session', 'build-tools', 'api', 'diagnostics'],
		related_modules: ['vite.ts'],
		related_declarations: [
			'analyzeFromFiles',
			'createAnalysisSession',
			'OnDuplicates',
			'VitePluginSvelteDocinfoOptions',
			'createSourceOptions',
		],
	},
	{
		slug: 'architecture',
		category: 'guide',
		Component: ArchitecturePage,
		related_tomes: ['introduction', 'api', 'session', 'vite-plugin'],
		related_modules: [],
		related_declarations: [],
	},
	{
		slug: 'session',
		category: 'guide',
		Component: SessionPage,
		related_tomes: ['introduction', 'vite-plugin', 'build-tools', 'api', 'diagnostics'],
		related_modules: ['session.ts', 'dep-resolver.ts'],
		related_declarations: [
			'createAnalysisSession',
			'AnalysisSession',
			'AnalysisSessionOptions',
			'SetFileOptions',
			'SetFileResult',
			'SetFilesResult',
			'QueryOptions',
			'ImportResolver',
		],
	},
	{
		slug: 'build-tools',
		title: 'build tools',
		category: 'guide',
		Component: BuildToolsPage,
		related_tomes: ['introduction', 'session', 'vite-plugin', 'api'],
		related_modules: ['source.ts', 'discovery.ts', 'source-config.ts', 'dep-resolver.ts'],
		related_declarations: [
			'SourceFileInfo',
			'discoverSourceFiles',
			'DiscoverSourceFilesOptions',
			'DiscoverSourceFilesResult',
			'createSourceOptions',
			'ModuleSourceOptions',
			'ImportResolver',
			'analyze',
			'analyzeFromFiles',
		],
	},
	{
		slug: 'output-format',
		title: 'output format',
		category: 'reference',
		Component: OutputFormatPage,
		related_tomes: ['introduction', 'cli', 'api', 'tags', 'diagnostics'],
		related_modules: ['types.ts', 'declaration-helpers.ts'],
		related_declarations: [
			'AnalyzeResultJson',
			'ModuleJson',
			'DeclarationJson',
			'MemberJson',
			'ComponentPropJson',
			'SnippetDeclarationJson',
			'ParameterJson',
			'OverloadJson',
			'GenericParamJson',
			'compactReplacer',
			'findTypeReferences',
			'buildTypeReferencePatterns',
		],
	},
	{
		slug: 'tags',
		category: 'reference',
		Component: TagsPage,
		related_tomes: ['introduction', 'output-format', 'diagnostics'],
		related_modules: ['tsdoc.ts'],
		related_declarations: ['ComponentPropJson', 'ParameterJson', 'OverloadJson'],
	},
	{
		slug: 'diagnostics',
		category: 'reference',
		Component: DiagnosticsPage,
		related_tomes: ['output-format', 'tags', 'api', 'cli', 'vite-plugin', 'session'],
		related_modules: ['diagnostics.ts'],
		related_declarations: [
			'Diagnostic',
			'DiagnosticKind',
			'DiagnosticSeverity',
			'hasErrors',
			'hasWarnings',
			'errorsOf',
			'warningsOf',
			'byKind',
			'formatDiagnostic',
		],
	},
	{
		slug: 'api',
		category: 'reference',
		Component: ApiPage,
		related_tomes: [
			'introduction',
			'architecture',
			'vite-plugin',
			'session',
			'build-tools',
			'output-format',
			'diagnostics',
		],
		related_modules: ['analyze.ts', 'types.ts', 'typescript-exports.ts'],
		related_declarations: [
			'analyze',
			'analyzeFromFiles',
			'createAnalysisSession',
			'AnalyzeResultJson',
			'ModuleJson',
			'DeclarationJson',
		],
	},
];
